### ISSUE TITLE
Unlocking the Power of Open Source: A Beginner's Guide - September 2023

### ISSUE THREAD

**Issue by nisalrenuja** [gcsrilanka/community-spotlight#1]
## Talk Proposal Submission
*Important: Rename your proposal title to the following format "Elevate Your Tech Journey: Unleash the Magic of Open Source - September 2023*

**Talk Title:** Unlocking the Power of Open Source: A Beginner's Guide - September 2023

🏷️**Speaker Name:** Nisal Renuja Palliyaguru

✉️**Speaker Title**: Software Engineer/Postman Student Leader

👩‍💻**Speaker Intro**
Nisal Renuja Palliyaguru is an experienced Software Engineer passionate about open source and tech education. With several years of active contribution to open source projects, Nisal is excited to share insights and inspire students to embark on their open source journey.

📞**Speaker Contact:**
- Email nrenuja@email.com
- X (Formerly Twitter) https://twitter.com/NisalRenuja
- Linkedin https://www.linkedin.com/in/nisalrenuja/

💡**The duration of the talk should be limited to 30 minutes.**

📖**Abstract of your talk**
In this engaging session, I will unravel the captivating world of open-source technology. From understanding the fundamentals of open source to practical tips on contributing to projects, this talk is tailored for beginner students. Key takeaways include the benefits of open-source involvement, success stories, and valuable resources to kickstart your open-source journey.

🤝**How will the talk help you and the community you represent?**
This talk will empower students to dive into the open source world, enhancing their tech skills and opening up opportunities for growth. Nisal aims to inspire a new generation of open-source enthusiasts, fostering a stronger tech community.

📝**Notes:**
- I am excited to present on the community call and is available on the specified date.
- All provided information is accurate.
- I have read and understood the speaker code of conduct.

🪧**Agreement:**

- [x] I confirm that I am able to present on the day of the community call. _(This can be found on the repository readme file._)

- [x] I confirm that all of the information I have provided above is accurate.

- [x] I have read and understood the speaker [code of conduct](https://github.com/GitHubExperts-LK/community-spotlight/blob/main/CODE_OF_CONDUCT.md).

_If you have any trouble submitting the proposal or have additional questions, feel free to reach out to us at [githubcommunitysl@gmail.com](mailto:githubcommunitysl@gmail.com)._

**Comment by Suvink** [comment]
Hi @nisalrenuja, This looks awesome!
One small change, Could you please change your Speaker Intro to 3rd person perspective? You can refer to [this](https://www.bizzabo.com/blog/conference-speaker-bio-examples-free-template) article and structure your bio. 

@hiranthaPeiris FYI

**Comment by nisalrenuja** [comment]
sure let me change

**Comment by Suvink** [comment]
Looks good now. Someone from our team will be in touch with you regarding the next steps. All the best!

**Comment by nisalrenuja** [comment]
Thank you for the update! I appreciate your prompt response and look forward to hearing from your team regarding the next steps. If you need any further information or have any additional questions, please don't hesitate to reach out. 🙌

**Comment by hiranthaPeiris** [comment]
Hi @nisalrenuja,
This looks promising. looking forward to seeing you at the community call. 
Let's have a chat in the upcoming days.

**Comment by Suvink** [comment]
Closing as completed.
