### ISSUE TITLE
Build React App using TypeScript, Collaborate with GitHub and Deploy on Azure - December

### ISSUE THREAD

**Issue by MasterLWA** [gcsrilanka/community-spotlight#3]
## Talk Proposal Submission
*Important: Rename your proposal title to the following format "TALK TITLE - MONTH TO BE CONSIDERED"*

**Talk Title:** Build React App using TypeScript, Collaborate with GitHub and Deploy on Azure - December

🏷️**Speaker Name:** Lakindu Widuranga Alwis

✉️**Speaker Title** Intern Software Engineer at Axiata Digital Labs | Founder of LWA Technologies

👩‍💻**Speaker Intro**
I'm an undergraduate at SLIIT, a self-taught Full-Stack developer, an Intern Software Engineer at Axiata Digital Labs, a Tech Blogger And a founder of LWA Technologies(Startup). 

📞**Speaker Contact:**
- Email [lakinduwiduranga@outlook.com]
- X (Formerly Twitter) [@masterlwa]
- Linkedin [linkedin.com/in/masterlwa]

💡**The duration of the talk should be limited to 30 minutes.**

📖**Abstract of your talk**
1. Introduction to session. 
2. Explain why we use TypeScript. 
3. Create a Simple React App with TypeScript and using GitHub CoPilot. 
4. Collab it with GitHub Repository and Explain.
5. explain CI/CD
6. Create an Azure resource and explain it. (Also, guide to get Azure offer from GitHub Student Developer Package)
7. Deploy it on Azure.
8. Give some tips to the Developers on how they can use productivity using GitHub CoPilot. Also, How to write clean and good code. 
9. QnA 

🤝**How will the talk help you and the community you represent?**
[ 
First thing, I'm seeking a chance to start doing Tech talks to the Tech Community and Hope this would be a great chance to start it. 

This session will help others to move from JavaScript to TypeScript when they work with React. Also, Deploy Their Project using Azure. Because a lot of beginner-level developers get stuck with that kinda of stage.   Also, I hope to show how I use Github Copilot to increase my Productivity and give some tips to make their projects more clean and productive. 
]

📝**Notes:**
[Use this section to append any information or links that you have mentioned above or would like us to see!]

🪧**Agreement:**

- [x] I confirm that I am able to present on the day of the community call. _(This can be found on the repository readme file._)

- [x] I confirm that all of the information I have provided above is accurate.

- [x] I have read and understood the speaker [code of conduct](https://github.com/GitHubExperts-LK/community-spotlight/blob/main/CODE_OF_CONDUCT.md).

_If you have any trouble submitting the proposal or have additional questions, feel free to reach out to us at [githubcommunitysl@gmail.com](mailto:githubcommunitysl@gmail.com)._

**Comment by avincodes** [comment]
Hi @MasterLWA, thank you for your submission. Please be kind enough to follow the naming format requested in the issue template and rename your issue.

**Comment by Suvink** [comment]
Hi @MasterLWA , this looks great. Quick question, would you be able to cover all these topics in 30mins? Usually we encourage speakers to have a 20mins talk and 10 mins QnA. WDYT?

**Comment by MasterLWA** [comment]
Hello @Suvink @avincodes , 
**Thank you both of you for responding to me**. We can cut some points and fix the time to 20 minutes. is it okay?

**Comment by Suvink** [comment]
Sounds alright to me. Would you be able to update the issue with the new abstract?

**Comment by MasterLWA** [comment]
Sure. I'll do it 🙃

**Comment by MasterLWA** [comment]
- Introduction to session.
- Explain why we use TypeScript. (Use already created React App)
- Collab it with GitHub Repository and Explain.
- Create an Azure resource and explain it. (Also, guide to get Azure offer from GitHub Student Developer Package)
- Deploy it on Azure.
- Give some tips to the Developers on how they can use productivity using GitHub CoPilot. Also, How to write clean and good code.
- QnA

**How about this? 🙃**

**Comment by MasterLWA** [comment]
@Suvink How is this abstract?

**Comment by avincodes** [comment]
Hey @MasterLWA please edit the original issue with the updated abstract!

**Comment by avincodes** [comment]
Hi @MasterLWA , 

Thank you for taking the time to submit your talk proposal. Unfortunately, we had to move forward with another talk proposal for December. If you still want your proposal to be considered for January, please change the issue title and update the month.

Good luck with your future endeavors!
