### ISSUE TITLE
AI and Ethics: A Delicate Dance in the Digital Age- November

### ISSUE THREAD

**Issue by NabeelahF** [gcsrilanka/community-spotlight#4]
## Talk Proposal Submission
*Important: Rename your proposal title to the following format "TALK TITLE - MONTH TO BE CONSIDERED"*

**Talk Title:** [AI and Ethics: A Delicate Dance in the Digital Age]

🏷️**Speaker Name:** [Nabeelah Faumi]

✉️**Speaker Title** [Ms]

👩‍💻**Speaker Intro**

[A 2nd year, AI and Data Science undergraduate, with an interest in AI ethics. The IEEE WIE Chairperson at IIT, and currently leading a team in the AUA Innovate Leader Camp, focusing on the ethical nuances of DSS. An aspiring AI researcher who aims to leverage AI for global benefit.]

📞**Speaker Contact:**
- Email [faumi.20222404@iit.ac.lk]
- X (Formerly Twitter) [I don't use X anymore:')]
- Linkedin [www.linkedin.com/in/nabeelah-ahamed-faumi]

💡**The duration of the talk should be limited to 30 minutes.**

📖**Abstract of your talk**
[This speech delves into the ethical implications surrounding artificial intelligence (AI) and urges for responsible innovation. A small introduction to AI ethics and its pivotal role will be given. Addressing concerns such as bias in algorithms, the lack of transparency, and the ethical considerations tied to privacy.  It also delves into the social impact of AI, emphasizing issues related to inequality, and the imperative for inclusivity and diversity.
The talk also scrutinizes the robustness and security of AI systems, highlighting the ethical responsibilities tied to their deployment. Furthermore, the role of governments and the establishment of international ethical standards in fostering responsible AI practices on a global scale will also be touched on.
The target audience is the general public, with more focus on those who are developing AI tools. This talk aims to increase awareness of AI and its ethical dilemma ]

🤝**How will the talk help you and the community you represent?**
[The talk helps raise awareness within the community about the importance of ethical considerations in technology development and provides valuable insights into specific ethical challenges associated with AI, fostering a deeper understanding among community members.  This will make people aware of the often-overlooked limitations of AI, thus enabling them to make more informed decisions when it comes to their daily interactions with AI.
As Sri Lankans, we are drastically underrepresented in the development of AI and the talk aims to inspire people to put their perspective on AI, and make their mark on this rapidly growing field.
The talk will allow me to get back into public speaking as I was an avid public speaker but haven't had much opportunity in the realm once I started university. It will also allow me to network and meet new people that I can take on mentors, and friends.]

📝**Notes:**
[Use this section to append any information or links that you have mentioned above or would like us to see!]

🪧**Agreement:**

- [X] I confirm that I can present on the day of the community call. _(This can be found on the repository readme file._)

- [X] I confirm that all of the information I have provided above is accurate.

- [X] I have read and understood the speaker [code of conduct](https://github.com/GitHubExperts-LK/community-spotlight/blob/main/CODE_OF_CONDUCT.md).

_If you have any trouble submitting the proposal or have additional questions, feel free to reach out to us at [githubcommunitysl@gmail.com](mailto:githubcommunitysl@gmail.com)._

**Comment by Suvink** [comment]
Hi @NabeelahF , this looks great! Small suggestion: Shall we rephrase your speaker bio to third person format? This article might help. [How To Write a Speaker Bio for a Conference (With Examples)](https://www.bizzabo.com/blog/conference-speaker-bio-examples-free-template)

**Comment by NabeelahF** [comment]
> Hi @NabeelahF , this looks great! Small suggestion: Shall we rephrase your speaker bio to third person format? This article might help. [How To Write a Speaker Bio for a Conference (With Examples)](https://www.bizzabo.com/blog/conference-speaker-bio-examples-free-template)

Thanks for letting me know, I've changed it.

**Comment by Suvink** [comment]
Hi @NabeelahF , Thank you so much for taking the time to submit your talk proposal. Unfortunately, we had to move forward with another talk proposal for November.
If you still want your proposal to be considered for December, please change the issue title and update the month.
Good luck with your future endaevours!
