### ISSUE TITLE
Molding a Gem : Future of Education with AI - November

### ISSUE THREAD

**Issue by ShihanAmbuldeniya** [gcsrilanka/community-spotlight#6]
## Talk Proposal Submission
*Important: Rename your proposal title to the following format "TALK TITLE - MONTH TO BE CONSIDERED"*

**Talk Title:** Molding a Gem: Future of Education with AI 

🏷️**Speaker Name:** Shihan Embuldeniya

✉️**Speaker Title:** Tech Innovator and Full Stack Developer  |  Founder of AcsteQ Technologies (Startup)

👩‍💻**Speaker Intro**
I'm Shihan Embuldeniya, a passionate self-taught full-stack developer currently pursuing a Micro Bachelor in Full Stack Development at IBM and an Associate degree in Engineering at Broward College, Florida. I'm deeply interested in AI and actively involved in research. My goal is to contribute to the exciting intersection of technology and artificial intelligence.

📞**Speaker Contact:**
- Email shihanambuldeniya@gmail.com
- X (Formerly Twitter) [@ShihanAcsteQ]
- Linkedin [linkedin.com/in/yourprofile]

💡**The duration of the talk should be limited to 30 minutes.**

📖**Abstract of your talk**
Education plays a pivotal role in shaping our civilization, and as the next generation, children hold a key stake in the future of AI. However, a widening gap exists between our current education system and the demands of the future. As an early adopter and young innovator leveraging AI to create award-winning products, I aim to address the challenges developers encounter when creating AI-based educational tools, the implications of AI in schools, the establishment of trust between parents and AI, and the potential for AI to revolutionize teaching methodologies for future generations.

Key Takeaway 1:	Gain insight into challenges in developing AI-based educational tools, and learn strategies to overcome them effectively.
Key Takeaway 2:	Understand AI's implications in school education, from personalized learning to equity, for informed decision-making.
Key Takeaway 3:	Discover insights for incorporating AI in early education, fostering critical thinking and skills development.

🤝**How will the talk help you and the community you represent?**
The talk I'm excited to share isn't just about AI, it's a chance for me to connect with the community and grow personally. By inspiring the community in developing AI based educational tools, I hope to provide insights into AI's impact on education, from personalized learning to equity. Personally, it's a valuable step in my own learning journey, and for the community, it's an opportunity to gain knowledge and inspiration for incorporating AI in early education.

📝**Notes:**
This is my session proposal that I submitted for Github Universe 2023, and I've been selected for the Alternate list. I would like to share my session at the GCSL Community Spotlight. Follow the link to see the feedback for my session from the Github Universe Team.
Google Drive link : https://drive.google.com/drive/folders/1BqHjhOLaLny2IzUtl4bEURY_NR7xmn_H?usp=sharing

🪧**Agreement:**

- [x] I confirm that I am able to present on the day of the community call. _(This can be found on the repository readme file._)

- [x] I confirm that all of the information I have provided above is accurate.

- [x] I have read and understood the speaker [code of conduct](https://github.com/GitHubExperts-LK/community-spotlight/blob/main/CODE_OF_CONDUCT.md).

_If you have any trouble submitting the proposal or have additional questions, feel free to reach out to us at [githubcommunitysl@gmail.com](mailto:githubcommunitysl@gmail.com)._

**Comment by ShihanAmbuldeniya** [comment]
Linkedin profile [linkedin.com/in/shihan-embuldeniya-24813b218]

**Comment by Suvink** [comment]
Hi @ShihanAmbuldeniya! Sounds amazing. Could you please rename the issue to the given title format? 

> Important: Rename your proposal title to the following format "TALK TITLE - MONTH TO BE CONSIDERED"

**Comment by ShihanAmbuldeniya** [comment]
Hi @Suvink please check whether the title format is correct now.

**Comment by Suvink** [comment]
Hi, you have to change the title from here > 
![Screenshot 2023-11-18 at 11 26 34](https://github.com/gcsrilanka/community-spotlight/assets/10671497/3a5b5724-3e41-4fdf-b4e2-b81dd4367038)

**Comment by ShihanAmbuldeniya** [comment]
@Suvink Done!

**Comment by Suvink** [comment]
Hi @ShihanAmbuldeniya , Congratulations 🥳 your talk proposal has been selected for this November community call. We'll let you know about the proceedings in a moment. Please keep an eye on your emails!

**Comment by ShihanAmbuldeniya** [comment]
Thank you for the Exciting News and considering my talk proposal @Suvink . Im honored to be selected as for the November community call at GCSL 🌟
